"""Confirmatory analysis per analysis/PREREGISTRATION.md.
Reads: data/work/agenterrorbench_annotations.csv, data/work/whowhen_reasons.csv,
       analysis/whowhen_coding.py, analysis/mapping.md (mapping encoded below).
Writes: data/work/coded.csv, analysis/RESULTS.md.
(Figures: analysis/make_figures.py.)
"""
import json, math, os
import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.makedirs(f"{BASE}/figures", exist_ok=True)

# ---- 1. AgentErrorBench: normalize + map ----
NATIVE2UNI = {
 ("memory","over_simplification"):"MEMORY",
 ("memory","memory_retrieval_failure"):"MEMORY",
 ("memory","hallucination"):"MEMORY",
 ("reflection","hallucination"):"MEMORY",
 ("reflection","progress_misjudge"):"OBS_MISREAD",
 ("reflection","outcome_misinterpretation"):"OBS_MISREAD",
 ("reflection","causal_misattribution"):"OBS_MISREAD",
 ("planning","constraint_ignorance"):"PLAN",
 ("planning","impossible_action"):"PLAN",
 ("planning","inefficient_plan"):"PLAN",
 ("action","misalignment"):"TOOL_SELECT",
 ("action","invalid_action"):"TOOL_FORMAT",
 ("action","format_error"):"TOOL_FORMAT",
 ("action","parameter_error"):"TOOL_FORMAT",
 ("system","step_limit"):"OTHER",
 ("system","tool_execution_error"):"TOOL_EXEC",
 ("system","llm_limit"):"TOOL_EXEC",
 ("system","environment_error"):"TOOL_EXEC",
 ("others","others"):"OTHER",
}
def norm_mod(m): return "planning" if m=="plan" else m
def norm_ft(ft):
    ft=(ft or "").strip().lower()
    return {"plan_inefficient":"inefficient_plan"}.get(ft,ft)

aeb = pd.read_csv(f"{BASE}/data/work/agenterrorbench_annotations.csv")
# rebuild with raw fields (csv has module/failure_type); recompute from source for fidelity
rows=[]
for f,tt in [("data/raw/agenterrorbench/Label/alfworld_labels.json","alfworld"),
              ("data/raw/agenterrorbench/Label/gaia_labels.json","gaia"),
              ("data/raw/agenterrorbench/Label/webshop_labels.json","webshop")]:
    for t in json.load(open(f"{BASE}/{f}")):
        for sa in t["step_annotations"]:
            for mod,ann in sa.items():
                if mod=="step": continue
                m, ft = norm_mod(mod), norm_ft(ann.get("failure_type",""))
                uni = NATIVE2UNI.get((m,ft), "UNMAPPABLE") if ft else "UNMAPPABLE"
                rows.append({"dataset":"AgentErrorBench","domain":tt,"llm":t["LLM"],
                             "native":f"{m}.{ft}" if ft else f"{m}.<empty>",
                             "unified":uni})
aeb_coded = pd.DataFrame(rows)

# ---- 2. Who&When: apply primary-analyst coding ----
import importlib.util
spec = importlib.util.spec_from_file_location("wc", f"{BASE}/analysis/whowhen_coding.py")
wc = importlib.util.module_from_spec(spec); spec.loader.exec_module(wc)
ww = pd.read_csv(f"{BASE}/data/work/whowhen_reasons.csv")
ww["unified"] = ww["row_id"].map(lambda i: wc.CODING[i][0])
ww["secondary"] = ww["row_id"].map(lambda i: wc.CODING[i][1])
# Adjudicated consensus overrides (independent second coding + adjudication 2026-09-27):
# rows where the second coder's label was held over coder 1's.
_cons = pd.read_csv(f"{BASE}/analysis/consensus_overrides.csv").set_index("row_id")["consensus_label"].to_dict()
ww["unified"] = ww.apply(lambda r: _cons.get(r["row_id"], r["unified"]), axis=1)
ww["dataset"]="Who&When"; ww["domain"]="multi-agent"
ww_coded = ww[["dataset","domain","unified"]].copy()
ww_coded["native"]="free-text reason (analyst-coded)"
ww_coded["llm"]="n/a"

coded = pd.concat([aeb_coded, ww_coded], ignore_index=True)
coded.to_csv(f"{BASE}/data/work/coded.csv", index=False)

CLASSES = ["PLAN","TOOL_SELECT","TOOL_FORMAT","TOOL_EXEC","OBS_MISREAD","GROUNDING",
           "NO_RECOVERY","LOOP","GIVE_UP","VERIFICATION","MEMORY","COORDINATION","OTHER","UNMAPPABLE"]

def wilson(k,n,z=1.96):
    if n==0: return (0,0)
    p=k/n; d=1+z*z/n; c=p+z*z/(2*n)
    m=z*math.sqrt(p*(1-p)/n+z*z/(4*n*n))
    return (max(0,(c-m)/d), min(1,(c+m)/d))

out=[]
out.append("# Results (generated by analysis/run_analysis.py)\n")
out.append(f"Total coded records: {len(coded)} (AgentErrorBench: {len(aeb_coded)}, Who&When: {len(ww_coded)})\n")

# RQ1: per-dataset distributions
out.append("## RQ1 — per-dataset unified distributions\n")
for ds in ["AgentErrorBench","Who&When"]:
    sub=coded[coded.dataset==ds]; n=len(sub)
    out.append(f"### {ds} (n={n})")
    for c in CLASSES:
        k=(sub.unified==c).sum()
        if k==0: continue
        lo,hi=wilson(k,n)
        out.append(f"- {c}: {k}/{n} ({k/n:.1%}, 95% CI {lo:.1%}–{hi:.1%})")
    out.append("")

# RQ2/RQ4 + H1: chi-square unified x dataset
ct = pd.crosstab(coded["unified"], coded["dataset"])
ct = ct.reindex([c for c in CLASSES if c in ct.index])
chi2,p,dof,exp = chi2_contingency(ct)
out.append("## H1 — chi-square: unified category x dataset\n")
out.append(f"chi2={chi2:.2f}, dof={dof}, p={p:.4g}")
out.append("H1 (distributions differ across datasets): "+"SUPPORTED (p<0.05)" if p<0.05 else "NOT supported")
out.append("")
out.append("Standardized residuals (cells with |r|>2):")
res=(ct-exp)/np.sqrt(exp)
for c in ct.index:
    for ds in ct.columns:
        r=res.loc[c,ds]
        if abs(r)>2: out.append(f"- {c} x {ds}: r={r:+.2f}")
out.append("")

# Domain comparison (RQ4): alfworld=embodied, webshop=web, gaia=general, multi-agent
dom = coded[coded.unified!="UNMAPPABLE"].copy()
ctd = pd.crosstab(dom["unified"], dom["domain"])
chi2d,pd_,dofd,expd = chi2_contingency(ctd)
out.append("## RQ4/H1b — chi-square: unified category x domain\n")
out.append(f"chi2={chi2d:.2f}, dof={dofd}, p={pd_:.4g}")
out.append("Domain distributions differ: "+"YES (p<0.05)" if pd_<0.05 else "NO")
out.append("")
out.append("Top-3 unified classes per domain:")
for d_ in ctd.columns:
    top=ctd[d_].sort_values(ascending=False).head(3)
    out.append(f"- {d_} (n={ctd[d_].sum()}): "+", ".join(f"{c} {v}" for c,v in top.items()))
out.append("")

# H2: PLAN plurality in web-nav vs multi-agent COORDINATION
def top1(sub):
    vc=sub["unified"].value_counts(); return vc.index[0], vc.iloc[0], len(sub)
for d_ in ["webshop","alfworld","gaia","multi-agent"]:
    t1,k,n=top1(dom[dom.domain==d_]); out.append(f"- {d_}: top1={t1} ({k}/{n}={k/n:.1%})")
w_top,_w,_n=top1(dom[dom.domain=="webshop"]); m_top,_m,_n2=top1(dom[dom.domain=="multi-agent"])
out.append(f"H2 (PLAN plurality in web-nav, COORDINATION plurality in multi-agent): "
           +("SUPPORTED" if (w_top=="PLAN" and m_top=="COORDINATION") else "NOT supported")+
           f" [webshop top1={w_top}, multi-agent top1={m_top}]")
out.append("")

# H3 + RQ5 coverage
unm=(coded.unified=="UNMAPPABLE").sum()
out.append("## H3 / coverage — UNMAPPABLE\n")
out.append(f"UNMAPPABLE overall: {unm}/{len(coded)} ({unm/len(coded):.1%})")
aeb_unm=(aeb_coded.unified=="UNMAPPABLE").sum()
out.append(f"AgentErrorBench native-label UNMAPPABLE: {aeb_unm}/{len(aeb_coded)} ({aeb_unm/len(aeb_coded):.1%})")
out.append("H3 (>=15% native labels UNMAPPABLE): "+("SUPPORTED" if aeb_unm/len(aeb_coded)>=0.15 else "NOT supported"))
out.append("")
# label-noise audit (RQ3 quantitative)
out.append("## RQ3 — label-noise audit (AgentErrorBench source data)\n")
out.append(f"- Empty failure_type: {aeb_unm}/200 ({aeb_unm/200:.1%}); by LLM: "
           +", ".join(f"{l} {((aeb_coded.llm==l)&(aeb_coded.unified=='UNMAPPABLE')).sum()}/{(aeb_coded.llm==l).sum()}"
                       for l in sorted(aeb_coded.llm.unique())))
out.append("- Inconsistent strings normalized: plan_inefficient/inefficient_plan, Parameter_error/parameter_error, trailing-space tool_execution_error, plan/planning module key")

with open(f"{BASE}/analysis/RESULTS.md","w") as f: f.write("\n".join(out))

# Figures are generated separately by analysis/make_figures.py (canonical
# publication designs); this script writes only data/work/coded.csv and
# analysis/RESULTS.md.
print(open(f"{BASE}/analysis/RESULTS.md").read()[:300])
print("... done (run analysis/make_figures.py to regenerate figures).")
