"""Primary-analyst coding of 184 Who&When free-text failure reasons into the unified 13-class scheme.
Coding guide (applied consistently):
- "code is incorrect/buggy" -> TOOL_FORMAT (produced artifact malformed)
- "plan is incorrect/wrong approach/false premise" -> PLAN
- "fails to verify / assumes without checking" -> VERIFICATION
- "fabricates/hallucinates/wrong facts" -> GROUNDING
- "misinterprets output" -> OBS_MISREAD
- "wrong tool / should have used X tool" -> TOOL_SELECT
- "tool returns error / cannot access / retrieval failed" -> TOOL_EXEC
- "orchestrator misdirects / role violation (multi-agent)" -> COORDINATION
- "repeated attempts, no progress" -> LOOP
- "empty/evasive / gives up / stops early" -> GIVE_UP
- "no mechanism given" -> OTHER (underspecified), with note
Codes: row_id -> (primary, secondary_or_None, note)
"""
CODING = {
0:("OTHER",None,"underspecified: fails to collect data, no mechanism"),
1:("TOOL_FORMAT",None,""),
2:("PLAN",None,""),
3:("TOOL_FORMAT",None,"buggy simulation implementation"),
4:("PLAN",None,"false assumption (video downloadable); step exhaustion is consequence"),
5:("GROUNDING",None,"not targeting correct elements"),
6:("OBS_MISREAD",None,"misinterprets OCR output"),
7:("TOOL_FORMAT",None,"code returns no output"),
8:("PLAN",None,"incorrect grammatical reasoning"),
9:("GROUNDING","TOOL_FORMAT","hallucinates video ID + placeholder data"),
10:("TOOL_FORMAT",None,""),
11:("GIVE_UP",None,"no useful information provided"),
12:("GROUNDING","VERIFICATION","incorrect addresses; should have gathered accurate info"),
13:("OTHER",None,"arithmetic rounding slip; no class fits"),
14:("TOOL_SELECT",None,"wrong tool chosen; web search more appropriate"),
15:("PLAN",None,"false premise: PDF assumed available"),
16:("TOOL_EXEC",None,"retrieval failure: correct URL not located"),
17:("GROUNDING",None,"wrong title identified"),
18:("TOOL_FORMAT",None,""),
19:("VERIFICATION",None,"did not verify rate; assumed from general knowledge"),
20:("VERIFICATION",None,"assumed value was 2020 estimate without verifying"),
21:("PLAN",None,"assumed unprovided file exists; wrong plan premise"),
22:("TOOL_FORMAT",None,""),
23:("OTHER",None,"underspecified: answer incorrect, no mechanism"),
24:("TOOL_FORMAT","COORDINATION","buggy code propagated to following experts"),
25:("VERIFICATION",None,"used unverified price in calculation"),
26:("LOOP",None,"repeated buggy code -> step exhaustion"),
27:("GROUNDING",None,"factual error: Thriller is an album not a song"),
28:("GROUNDING",None,"incorrect film list"),
29:("TOOL_FORMAT",None,"unreasonable code"),
30:("PLAN",None,"flawed conversion method"),
31:("GROUNDING",None,"fabricated population figures"),
32:("GROUNDING",None,"unsupported quantitative assumption (20 blocks/mile)"),
33:("OTHER",None,"underspecified: irrelevant info, no mechanism"),
34:("PLAN",None,"incorrect plan; note: question itself inaccurate"),
35:("VERIFICATION",None,"assumed schedule correct without verifying"),
36:("GIVE_UP",None,"conclusion without taking any actions"),
37:("GROUNDING",None,"fabricated data-collection process"),
38:("COORDINATION","VERIFICATION","failed to catch other agents' bad info"),
39:("GROUNDING",None,"wrong year extracted (2022 vs 2017)"),
40:("TOOL_FORMAT",None,""),
41:("TOOL_FORMAT",None,""),
42:("VERIFICATION",None,"no verification before concluding"),
43:("OBS_MISREAD",None,"misread transcription: fresh->ripe strawberries"),
44:("VERIFICATION",None,"concluded without verifying search results"),
45:("VERIFICATION",None,"wrong final answer reached without verification"),
46:("GROUNDING",None,"wrong place identified"),
47:("PLAN",None,"misunderstood the problem (goal misunderstanding)"),
48:("TOOL_SELECT",None,"YouTube tools more appropriate"),
49:("PLAN",None,"incorrect plan"),
50:("TOOL_FORMAT",None,"placeholder values in code"),
51:("TOOL_FORMAT",None,"edge-case bug"),
52:("GROUNDING",None,"wrong headstone identified -> wrong extraction"),
53:("GROUNDING",None,"factual inaccuracies"),
54:("TOOL_FORMAT",None,"missing import"),
55:("GIVE_UP",None,"stopped examining results early"),
56:("TOOL_FORMAT",None,"extracting nonexistent columns"),
57:("LOOP",None,"incorrect code twice -> limit exhaustion"),
58:("PLAN",None,"logical reasoning error"),
59:("TOOL_FORMAT",None,""),
60:("GROUNDING",None,"simulated dataset presented instead of real data"),
61:("TOOL_FORMAT",None,"inappropriate code"),
62:("TOOL_SELECT",None,"suggested manual extraction over Python"),
63:("TOOL_FORMAT",None,"code not working; ambiguous but likely buggy"),
64:("TOOL_FORMAT",None,""),
65:("GROUNDING",None,"stale internal knowledge presented as current fact"),
66:("PLAN","VERIFICATION","false premise (1000 articles); should have checked"),
67:("TOOL_FORMAT",None,""),
68:("TOOL_FORMAT",None,""),
69:("GROUNDING",None,"wrong setting selected"),
70:("PLAN",None,"debugging diverted from actual question"),
71:("VERIFICATION",None,"verification done wrong (summary vs relevant link)"),
72:("COORDINATION",None,"role disobedience: validation doing analysis"),
73:("COORDINATION","VERIFICATION","did not challenge suspicious 0% result"),
74:("PLAN",None,"false premise: assumed regular hexagon"),
75:("OBS_MISREAD",None,"inaccurate summary; overlooked query constraints"),
76:("GROUNDING",None,"incorrect initial information"),
77:("TOOL_FORMAT",None,"placeholder values in code"),
78:("OBS_MISREAD",None,"conflated issue-close time with label-added time"),
79:("PLAN",None,"hasty strategy; should investigate stepwise"),
80:("TOOL_SELECT",None,"web search instead of PDF download+extract"),
81:("TOOL_FORMAT",None,""),
82:("GROUNDING","VERIFICATION","fabricated website content; no verification"),
83:("TOOL_FORMAT",None,""),
84:("OTHER",None,"underspecified: answer incorrect"),
85:("TOOL_FORMAT","LOOP","repeatedly incorrect code -> false conclusion"),
86:("TOOL_FORMAT",None,"NaN-handling bug"),
87:("GROUNDING",None,"factual error in execution result"),
88:("GROUNDING",None,"false claim about album grade"),
89:("VERIFICATION",None,"answered on assumption"),
90:("OTHER",None,"arithmetic error; no class fits"),
91:("GROUNDING",None,"hallucinated notes without viewing image"),
92:("TOOL_SELECT",None,"pandas inadequate for color data; wrong tool"),
93:("GROUNDING",None,"incorrect/hypothetical data provided"),
94:("PLAN",None,"steps irrelevant to question"),
95:("LOOP",None,"repeated buggy code -> step exhaustion"),
96:("GROUNDING","VERIFICATION","incorrect prices; should obtain accurate info"),
97:("VERIFICATION",None,"provided poem text without retrieving"),
98:("PLAN",None,"incorrect plan"),
99:("GROUNDING",None,"wrong actor name"),
100:("GROUNDING",None,"incorrect price propagated"),
101:("OTHER",None,"underspecified: incorrectly present problems"),
102:("TOOL_FORMAT",None,"unreasonable code"),
103:("TOOL_FORMAT",None,"incorrect and unrelated code"),
104:("TOOL_FORMAT",None,"missing table imports -> step exhaustion"),
105:("TOOL_EXEC",None,"failed to retrieve info from paper link"),
106:("PLAN",None,"wrong direction; failed to locate target"),
107:("TOOL_SELECT",None,"required tool (web search) not invoked"),
108:("OTHER",None,"underspecified: answer incorrect"),
109:("TOOL_FORMAT",None,"DFS implementation bug"),
110:("OTHER",None,"underspecified: answer incorrect"),
111:("TOOL_SELECT","TOOL_FORMAT","manual inspection suggested over tools; bad code too"),
112:("VERIFICATION",None,"answered without taking necessary actions"),
113:("TOOL_FORMAT",None,""),
114:("VERIFICATION",None,"no image analysis before concluding"),
115:("TOOL_FORMAT",None,""),
116:("VERIFICATION",None,"did not verify ZIP codes against USGS"),
117:("GROUNDING",None,"generated data presented as answer"),
118:("PLAN",None,"task description misaligned with question"),
119:("GROUNDING",None,"wrong command identified"),
120:("GROUNDING",None,"incorrect movie list"),
121:("TOOL_FORMAT",None,"missing imports"),
122:("TOOL_FORMAT",None,""),
123:("GROUNDING",None,"incorrect citation text"),
124:("PLAN",None,"false premise in game-theoretic reasoning"),
125:("TOOL_SELECT",None,"Bing search instead of page-history review"),
126:("TOOL_EXEC",None,"unreliable document access"),
127:("COORDINATION",None,"orchestrator poor instruction; wrong conclusion from partial page"),
128:("OBS_MISREAD",None,"misinterpreted/failed Latin root retrieval"),
129:("COORDINATION",None,"orchestrator failed to direct scrolling/filter use"),
130:("TOOL_FORMAT",None,"query not concise -> time limit"),
131:("VERIFICATION",None,"did not verify house-price claim"),
132:("VERIFICATION",None,"conclusion without correct actions (screenshot/extract)"),
133:("GROUNDING",None,"orchestrator guessed on assumptions after poor retrieval"),
134:("TOOL_FORMAT",None,"insufficient keyword"),
135:("TOOL_FORMAT","VERIFICATION","missing search criterion; wrong conclusion"),
136:("TOOL_FORMAT",None,"keyword should include site"),
137:("TOOL_EXEC",None,"difficulty accessing acknowledgment section"),
138:("TOOL_FORMAT",None,"orchestrator wrote incorrect code"),
139:("COORDINATION",None,"orchestrator acted on incomplete subordinate output"),
140:("TOOL_EXEC",None,"audio transcription failed"),
141:("GROUNDING","VERIFICATION","wrong extraction + unverified wrong answer"),
142:("COORDINATION",None,"role disobedience: wrong direction for agent group"),
143:("VERIFICATION",None,"did not confirm gym-list completeness"),
144:("TOOL_EXEC",None,"incomplete data retrieval from journal site"),
145:("GROUNDING",None,"clicked irrelevant website (wrong element)"),
146:("GROUNDING",None,"incorrect information obtained"),
147:("PLAN",None,"failed to recognize expandable-tab affordance; wrong strategy"),
148:("TOOL_EXEC",None,"search tool returned no desired info"),
149:("GROUNDING",None,"unreliable info obtained"),
150:("GROUNDING",None,"wrong search result"),
151:("GROUNDING",None,"factual errors in calculation basis"),
152:("GROUNDING",None,"wrong list (omission+substitution)"),
153:("OTHER",None,"underspecified: error processing data"),
154:("COORDINATION",None,"orchestrator gave incorrect instructions"),
155:("OTHER",None,"underspecified: translation error, no mechanism"),
156:("PLAN",None,"wrong reasoning process"),
157:("VERIFICATION","GROUNDING","answered without enough info (unsupported)"),
158:("GIVE_UP",None,"task left incomplete (revisions uncounted)"),
159:("TOOL_EXEC",None,"errors encountered during process"),
160:("TOOL_EXEC",None,"retrieval returned nothing useful"),
161:("OTHER",None,"UI interaction failure; mechanism ambiguous"),
162:("TOOL_EXEC",None,"gym missing from search results"),
163:("TOOL_EXEC",None,"no useful info returned"),
164:("PLAN",None,"failed to plan APOD link navigation"),
165:("TOOL_FORMAT",None,"poorly refined queries"),
166:("GROUNDING",None,"failed to select useful info (wrong element by omission)"),
167:("TOOL_EXEC","GROUNDING","404 access failure -> incorrect guess"),
168:("OTHER",None,"possibly absent info; may not be an agent failure"),
169:("COORDINATION",None,"orchestrator poor verification-direction"),
170:("VERIFICATION",None,"over-relied on search instead of visiting TripAdvisor"),
171:("COORDINATION","LOOP","orchestrator misdirection + repetition"),
172:("TOOL_FORMAT",None,""),
173:("OTHER",None,"underspecified: calculation wrong"),
174:("VERIFICATION",None,"concluded without gathering enough info; should replan"),
175:("VERIFICATION",None,"relied on third-party vs official source"),
176:("PLAN",None,"missed temporal constraint (July 2023 roster)"),
177:("TOOL_EXEC",None,"OCR produced wrong text"),
178:("COORDINATION",None,"wrong orchestrator instruction"),
179:("COORDINATION",None,"orchestrator overrode subordinate prematurely"),
180:("TOOL_EXEC",None,"extraction from Issue page failed"),
181:("TOOL_EXEC",None,"no useful info returned"),
182:("COORDINATION","VERIFICATION","orchestrator replanned instead of verifying"),
183:("TOOL_EXEC",None,"OCR price extraction failed"),
}
